name: 'Setup Python Environment'
description: 'Checkout code, setup Python, and install dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt
