name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install flake8
        run: pip install flake8
      
      - name: Run lint check
        run: flake8 . --max-line-length=100
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10','3.11','3.12']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -v
  check-secret:
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
      APP_VERSION: "1.0.0"
    steps:
      - name: Show normal env vars
        run: |
          echo "Environment: $APP_ENV"
          echo "Version: $APP_VERSION" 

      - name: Use the repo secret
        env:
          MY_SECRET: ${{secrets.THE_WORLD}}
        run: |
          echo "Secret length check:"
          echo -n "$MY_SECRET" | wc -c
  check-env-secret:
    runs-on: ubuntu-latest
    Environment: Enji
    steps:
      - name: Use the env secret
        env:
         MY_SECRET: ${{secret.ENV}}
        run: |
          echo "Environment secret length check:"
          echo -n "$MY_SECRET" | wc - c