name: My First CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Hello, More steps!"

      - name: Show current date
        run: date

      - name: List files in workspace
        run: ls -la