name: Test CI/CD By MySelf

on: 
  push:
    branches:
      - main

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python --version
      - run: pip install -r requirements.txt
      - run: pytest -v
        
